"""
Application entrypoint for compressibility correction postprocessing.

This stage reads the aerodynamic results generated by XFOIL at Mach 0.2
and applies compressibility corrections to approximate behavior at higher
representative Mach numbers for each flight condition.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import matplotlib.pyplot as plt
import pandas as pd

from vfp_analysis import config as base_config
from vfp_analysis.compressibility import config as comp_config
from vfp_analysis.compressibility.adapters.correction_models.prandtl_glauert_model import (
    PrandtlGlauertModel,
)
from vfp_analysis.compressibility.adapters.filesystem.corrected_results_writer import (
    FilesystemResultsWriter,
)
from vfp_analysis.compressibility.adapters.filesystem.polar_reader import (
    FilesystemPolarReader,
)
from vfp_analysis.compressibility.core.domain.compressibility_case import (
    CompressibilityCase,
)
from vfp_analysis.compressibility.core.services.compressibility_correction_service import (
    CompressibilityCorrectionService,
)

LOGGER = logging.getLogger(__name__)


def _find_polar_files(
    base_dir: Path, flight: str, section: Optional[str] = None
) -> list[Path]:
    """Find polar CSV files for a flight condition and optional section."""
    if section:
        polar_path = base_dir / flight.lower() / section / "polar.csv"
    else:
        polar_path = base_dir / flight.lower() / "polar.csv"

    if polar_path.is_file():
        return [polar_path]
    return []


def main() -> None:
    """Run compressibility correction stage."""
    LOGGER.info("=== Compressibility correction stage ===")

    comp_config.CORRECTED_RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    # Initialize adapters and service
    reader = FilesystemPolarReader()
    writer = FilesystemResultsWriter()
    model = PrandtlGlauertModel()
    service = CompressibilityCorrectionService(
        polar_reader=reader,
        results_writer=writer,
        correction_model=model,
        base_output_dir=comp_config.CORRECTED_RESULTS_DIR,
    )

    # Process each flight condition
    base_input = base_config.RESULTS_DIR / "final_analysis"
    flights = ["Takeoff", "Climb", "Cruise", "Descent"]
    sections = ["root", "mid_span", "tip"]

    all_results: list[dict] = []

    for flight in flights:
        target_mach = comp_config.TARGET_MACH[flight]
        case = CompressibilityCase(
            flight_condition=flight,
            target_mach=target_mach,
            reference_mach=comp_config.REFERENCE_MACH,
        )

        # Process each section
        for section in sections:
            polar_path = base_input / flight.lower() / section / "polar.csv"
            if not polar_path.is_file():
                LOGGER.warning(f"Polar not found: {polar_path}")
                continue

            LOGGER.info(
                f"Correcting {flight} / {section} (M={target_mach:.2f})"
            )

            result = service.correct_case(case, polar_path, section)

            # Extract max efficiency (second peak, alpha >= 3)
            df_corrected = pd.read_csv(result.corrected_polar_path)
            df_second = df_corrected[df_corrected["alpha"] >= 3.0]
            if not df_second.empty:
                idx = df_second["ld_corrected"].idxmax()
                row = df_second.loc[idx]
                all_results.append(
                    {
                        "flight": flight,
                        "section": section,
                        "mach_corrected": target_mach,
                        "alpha_opt_deg": float(row["alpha"]),
                        "ld_max_corrected": float(row["ld_corrected"]),
                    }
                )

    # Generate summary CSV
    if all_results:
        summary_df = pd.DataFrame(all_results)
        summary_path = comp_config.CORRECTED_RESULTS_DIR / "corrected_efficiency_summary.csv"
        summary_df.to_csv(summary_path, index=False, float_format="%.6f")
        LOGGER.info(f"Summary saved to {summary_path}")

    # Generate global comparison plots
    _generate_global_plots(base_input, comp_config.CORRECTED_RESULTS_DIR, flights)

    LOGGER.info("=== Compressibility correction stage completed ===")


def _generate_global_plots(
    input_dir: Path, output_dir: Path, flights: list[str]
) -> None:
    """Generate global comparison plots for all flight conditions."""
    # Plot: Corrected CL/CD vs alpha for all flights
    fig, ax = plt.subplots(figsize=(7.0, 5.0))
    for flight in flights:
        corrected_path = output_dir / flight.lower() / "mid_span" / "corrected_efficiency.csv"
        if corrected_path.is_file():
            df = pd.read_csv(corrected_path)
            ax.plot(
                df["alpha"],
                df["ld_corrected"],
                label=flight,
                linewidth=1.6,
            )
    ax.set_xlabel(r"$\alpha$ [deg]")
    ax.set_ylabel(r"$C_L/C_D$ corregido")
    ax.set_title("Eficiencia corregida $C_L/C_D$ por condición de vuelo")
    ax.grid(True, linestyle=":", linewidth=0.5, alpha=0.7)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(
        output_dir / "corrected_efficiency_all_flights.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close(fig)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    main()
